Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,41 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Enforce Version Label
+name: Version NPM package
 
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
+#on:
+#  pull_request:
+#    types: [labeled, unlabeled, opened, edited, syncronize]
+#    branches: [ master ]
 on:
   pull_request:
-    types: [labeled, unlabeled, opened, edited, synchronize]
+    types: [closed]
     branches: [ master ]
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   release:
+    name: "Release if we have a version label"
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
 
-      - name: Actions Ecosystem Action Release Label
-        uses: actions-ecosystem/action-release-label@v1.2.0
-        id: release-label
-        with:
-          # A prefix for labels that indicate semver level ({major, minor, patch}).
-          label_prefix: version-
-        
-      - name: Enforce release label
-        id: enforce-pr-label
-        run: exit 1
-        if: ${{ steps.release-label.outputs.level == null }}
+    - name: Get Version Label
+      uses: actions-ecosystem/action-release-label@v1.2.0
+      id: version-label
+      with:
+        # A prefix for labels that indicate semver level ({major, minor, patch}).#
+        label_prefix: version-
 
-  #enforce-label:
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #  - uses: yogevbd/enforce-label-action@2.1.0
-  #    with:
-  #      REQUIRED_LABELS_ANY: "version-major,version-minor,version-patch"
-  #      REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['version-major','version-minor','version-patch']"
+    - name: Debug Release Label
+      run: |
+        echo "${{ toJson(github.event.pull_request.labels) }}"
+        echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
+        echo "${{ github.event.pull_request.merged }}"
+      
+    #- name: NPM Version #test
+    #  if: ${{ steps.version-label.outputs.level != null }}
+    #  
+    #  run: |
+    #    echo "::error PR's to master with a 'version-*' label require a 'release' label"
+    #    exit 1
